[package]
name = "merka-vault"
version = "0.1.0"
edition = "2021"
description = "Vault provisioning and management crate integrating with merka-core"
license = "MIT OR Apache-2.0"
repository = "https://github.com/cosmicrocks/merka-vault"
documentation = "https://docs.rs/merka-vault"
keywords = ["vault", "pki", "hashicorp-vault", "merka", "cli", "actor"]
categories = ["api-bindings", "security", "dev-tools"]

[dependencies]
actix = "0.13.5"
actix-rt = "2.10.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros"] }
vaultrs = "0.7.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
thiserror = "2.0.11"
clap = { version = "4.5.30", features = ["derive", "env"] }
openssl = "0.10.71"
reqwest = { version = "0.12.12", features = ["json"] }
futures-util = "0.3.31"
anyhow = "1.0.95"
once_cell = "1.20.3"

[dev-dependencies]
tokio-test = "0.4.4"
testcontainers = "0.23.2"
lazy_static = "1.5.0"
env_logger = "0.11.6"
