services:
  vault:
    image: hashicorp/vault:1.18.4
    container_name: merka-vault-root
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: ["server"]
    volumes:
      - ./config/vault.hcl:/vault/config/vault.hcl
    networks:
      - vault-network

  # Sub vault that will be auto-unsealed by the root vault
  sub-vault:
    image: hashicorp/vault:1.18.4
    container_name: merka-vault-sub
    ports:
      - "8202:8200"
    cap_add:
      - IPC_LOCK
    command: ["server"]
    volumes:
      - ./config/vault.hcl:/vault/config/vault.hcl
    depends_on:
      - vault
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge
