---
name: CI
on: [push, pull_request]
jobs:
  rust:
    uses: esomore/ghworkflow-rust/.github/workflows/rust.yml@esomore-fix-codecov-action
    permissions:
      contents: read
      issues: write
    with:
      coveralls: true
      codecov: true
      deb: true
      publish_packagecloud_repository: |
        ["debian/debian/bookworm", "ubuntu/ubuntu/jammy"]
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
