---
name: CI
on: [push, pull_request]
jobs:
  rust:
    uses: esomore/ghworkflow-rust/.github/workflows/rust.yml@main
    permissions:
      issues: write
      attestations: write
      contents: write
      packages: write
    with:
      coveralls: false
      codecov: false
      publish_cratesio: true
      publish_github_release: false
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
