---
name: CI
on: [push, pull_request]
jobs:
  rust:
    uses: esomore/ghworkflow-rust/.github/workflows/rust.yml@esomore-fix-codecov-action
    permissions:
      contents: read
      issues: write
    with:
      coveralls: true
      codecov: true
      publish_cratesio: true
      publish_github_release: true
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
