---
name: CI
on: [push, pull_request]
jobs:
  rust:
    uses: lpenz/ghworkflow-rust/.github/workflows/rust.yml@v0.23.3
    with:
      coveralls: true
      codecov: true
      deb: true
      publish_packagecloud_repository: |
        ["debian/debian/bookworm", "ubuntu/ubuntu/jammy"]
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
